version: 2
jobs:
  build:
    working_directory: ~/scattersphere
    docker:
      - image: circleci/java:latest
    steps:
      - checkout
      - run:
          name: Compile the project
          command: sh scripts/circle/build.sh
      - run:
          name: Test
          command: sh scripts/circle/test.sh
      - run:
          name: Scala Documentation
          command: sh scripts/circle/doc.sh
      - store_artifacts:
          path: scattersphere-core/target/site/scaladocs
